# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=exampleTest
    ports:
      - '3306:3306'
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
